# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Casi McDaniels
email: casimcdaniels@gmail.com
description: Casi McDaniels - Web Developer and Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://casimcdaniels.com" # the base hostname & protocol for your site
github_username:  casimcdaniels

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - bower_components
  - bower.json
  - gulpfile.js
  - package.json
  - Rakefile
  - node_modules
  - README.md
  - LICENSE
